# Wine è una classificazione

In [1]:
import pandas as pd
import pickle

object = pd.read_pickle(r'/Users/paolo/Documents/projects/Projects/Magre/feature_selection/data/real/wine.pickle')
with open('/Users/paolo/Documents/projects/Projects/Magre/feature_selection/data/real/wine.pickle', 'rb') as fp:
            data = pickle.load(fp)

In [3]:
print(data['X'].shape)

(178, 13)


In [9]:
print(type(data['X']))

<class 'numpy.ndarray'>


## 1) usando la feature selection "con bug" tornano i risultati del paper (usando un altro metodo)

In [12]:
with open('/Users/paolo/Documents/projects/Projects/Magre/feature_selection/dataset_win_backward_res.pickle', 'rb') as fp:
            res = pickle.load(fp)

In [29]:
print(fp[0].selected,'\n',fp[1].selected,'\n',fp[2].selected,'\n',fp[3].selected,'\n',fp[4].selected,'\n',fp[5].selected,'\n',fp[6].selected,'\n',fp[7].selected)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12] 
 [ 0  3  4  5  6  7  8  9 10 11 12] 
 [ 0  3  4  7  9 10 12] 
 [ 0  3  4 12] 
 [ 4 12] 
 [ 4 12] 
 [ 4 12]


In [32]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

svmC1 = SVC(kernel="rbf", gamma='auto', C=1.0)
svmHighC = SVC(kernel="rbf", gamma='auto', C=10.0)
svmLowC = SVC(kernel="rbf", gamma='auto', C=0.1)

Xtrain, Xtest, Ytrain, Ytest = train_test_split(data['X'], data['Y'])

In [40]:
print(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]])

[[1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.187e+01 4.310e+00 2.390e+00 ... 7.500e-01 3.640e+00 3.800e+02]
 [1.367e+01 1.250e+00 1.920e+00 ... 1.230e+00 2.460e+00 6.300e+02]
 ...
 [1.406e+01 1.630e+00 2.280e+00 ... 1.090e+00 3.710e+00 7.800e+02]
 [1.372e+01 1.430e+00 2.500e+00 ... 8.900e-01 2.870e+00 1.285e+03]
 [1.221e+01 1.190e+00 1.750e+00 ... 1.280e+00 3.070e+00 7.180e+02]]


In [42]:
svmC1.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)
svmHighC.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)
svmLowC.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)

SVC(C=0.1, gamma='auto')

In [44]:
a = svmC1.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)
b = svmHighC.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)
c = svmLowC.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)

In [46]:
print(a,b,c)

0.35555555555555557 0.35555555555555557 0.35555555555555557


In [65]:
print(Ytrain)

[3 2 2 2 2 3 3 2 2 2 2 3 3 3 2 3 1 2 3 2 3 2 1 1 1 3 2 2 1 2 1 1 1 1 1 2 3
 3 1 3 2 2 3 3 2 3 2 3 2 2 3 2 1 3 3 2 2 3 2 2 1 2 2 3 1 1 1 2 3 1 2 1 2 1
 1 2 1 1 3 2 3 2 3 2 2 2 1 3 1 3 2 2 1 1 2 2 2 1 1 3 2 2 3 3 1 2 2 2 1 1 1
 1 1 1 2 3 2 2 2 2 2 1 1 1 1 3 3 1 3 1 1 1 2]


In [76]:
from sklearn.svm import SVC
from sklearn.tree import ExtraTreeClassifier

from sklearn.model_selection import train_test_split

ETC = ExtraTreeClassifier()

Xtrain, Xtest, Ytrain, Ytest = train_test_split(data['X'], data['Y'])

#ETC.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#ETC.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)

#ETC.fit(Xtrain[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#ETC.score(Xtest[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytest)

#ETC.fit(Xtrain[:, [0,3,4,7,9,10,12]], Ytrain)
#ETC.score(Xtest[:, [0,3,4,7,9,10,12]], Ytest)

#ETC.fit(Xtrain[:, [0,3,4,12]], Ytrain)
#ETC.score(Xtest[:, [0,3,4,12]], Ytest)

In [ ]:
from sklearn.svm import SVC
from sklearn.tree import ExtraTreeClassifier

from sklearn.model_selection import train_test_split

ETC = ExtraTreeClassifier()

Xtrain, Xtest, Ytrain, Ytest = train_test_split(data['X'], data['Y'])

#ETC.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#ETC.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)

#ETC.fit(Xtrain[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#ETC.score(Xtest[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytest)

#ETC.fit(Xtrain[:, [0,3,4,7,9,10,12]], Ytrain)
#ETC.score(Xtest[:, [0,3,4,7,9,10,12]], Ytest)

#ETC.fit(Xtrain[:, [0,3,4,12]], Ytrain)
#ETC.score(Xtest[:, [0,3,4,12]], Ytest)

In [158]:
from sklearn.svm import SVC
from sklearn.tree import ExtraTreeClassifier

from sklearn.model_selection import train_test_split

SVM_C = SVC()

Xtrain, Xtest, Ytrain, Ytest = train_test_split(data['X'], data['Y'])

#SVM_C.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#SVM_C.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)

#SVM_C.fit(Xtrain[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#SVM_C.score(Xtest[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytest)

#SVM_C.fit(Xtrain[:, [0,3,4,7,9,10,12]], Ytrain)
#SVM_C.score(Xtest[:, [0,3,4,7,9,10,12]], Ytest)

#SVM_C.fit(Xtrain[:, [0,3,4,12]], Ytrain)
#SVM_C.score(Xtest[:, [0,3,4,12]], Ytest)

0.6666666666666666

In [170]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(multi_class='multinomial',max_iter=10000)

#LR.fit(Xtrain[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#LR.score(Xtest[:, [ 0,1,2,3,4,5,6,7,8,9,10,11,12]], Ytest)
# 0.9555555555555556

#LR.fit(Xtrain[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytrain)
#LR.score(Xtest[:, [0,3,4,5,6,7,8,9,10,11,12]], Ytest)
# 0.9333333333333333

#LR.fit(Xtrain[:, [0,3,4,7,9,10,12]], Ytrain)
#LR.score(Xtest[:, [0,3,4,7,9,10,12]], Ytest)
# 0.8444444444444444

LR.fit(Xtrain[:, [0,3,4,12]], Ytrain)
LR.score(Xtest[:, [0,3,4,12]], Ytest)
# 0.8888888888888888

0.8888888888888888

In [23]:
dataset=['nome',object]
print(len(dataset))
print(data["X"].shape)
print(data["X"].shape[0]//20)

2
(178, 13)
8


## 2) usando la FS custom "non buggata" le CMI sono negative

Ha senso, il target è categorico e lo stimatore implementato è continuo!

-0.0404135338345859, 0
-0.0404135338345859, 1
-0.04077162737707063, 12
-0.05636249715197028, 11
-0.04696210222525998, 7
-0.04807546254914685, 10
-0.0453178400546812, 2
-0.04185419843314486, 5
-0.053934077618287724, 8
-0.05814475833272814, 6
-0.05608475658275758, 4
-0.014968442160926632, 3
tiene infine la 9

## 3) Mutual Information with scikit-learn --> viene sensata, tiene conto dei valori categorici, ma univariata!

In [ ]:
con più di una feature non è reliable. Calcola la MI fra ciascuna feature e il target, non va bene.

In [32]:
import pandas as pd
import pickle
import numpy as np
from sklearn.feature_selection import mutual_info_classif,mutual_info_regression
from sklearn.model_selection import train_test_split
import scripts.entropy_estimators as ee

In [15]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data['X'], data['Y'])

In [16]:
MI_estimates = mutual_info_classif(data['X'], data['Y'], n_neighbors=8)

In [17]:
print(MI_estimates)

[0.45112532 0.28361621 0.12135706 0.2388463  0.19341533 0.4001019
 0.69318873 0.15492481 0.22265654 0.55248673 0.44776843 0.54648898
 0.56473595]


In [ ]:
### Calcolo la conditional con la chain rule

In [25]:
Y = data['Y']
X = data['X'][:,0]
Z = data['X'][:,1:]

In [60]:
# MI fra X e Z
MI_XZ = mutual_info_regression(Z,X, n_neighbors=8)
MI_XZ

array([0.10798022, 0.09634506, 0.09036841, 0.08104234, 0.17045062,
       0.25903193, 0.03759561, 0.14373892, 0.34240903, 0.09122175,
       0.1054235 , 0.26218111])

In [65]:
# MI fra X e (Y,Z)

ZY = np.concatenate((Z,Y.reshape(-1,1)),axis=1)
MI_XYZ = mutual_info_regression(ZY,X, n_neighbors=8)
MI_XYZ

array([0.10972553, 0.09387656, 0.09989507, 0.08254819, 0.16972341,
       0.26087486, 0.03804636, 0.1440737 , 0.34434988, 0.09226397,
       0.1019038 , 0.26142439, 0.45439996])

# 4) Nuova Libreria

In [67]:
help(ee.cmi)

Help on function cmi in module scripts.entropy_estimators:

cmi(x, y, z, k=3, base=2)
    Mutual information of x and y, conditioned on z
    Legacy function. Use mi(x, y, z) directly.



In [70]:
Xi = []
Yi = []
Zi = []
for i in range(len(data['Y'])):
    Xi.append([data['X'][i,0]])
    Yi.append([data['Y'][i]])
    Zi.append(data['X'][i,1:].tolist())

In [77]:
ee.cmi(Xi,Yi,Zi, k=8)

-0.18794151807092968

In [85]:
for j in range(13):
    Xi = []
    Yi = []
    Zi = []
    for i in range(len(data['Y'])):
        Xi.append([data['X'][i,j]])
        Yi.append([data['Y'][i]])
        Zi.append(np.delete(data['X'],j,1)[i,:].tolist())
    #print(Xi[0])
    #print(Yi[0])
    #print(Zi[0])
    print(ee.cmi(Xi,Yi,Zi,k=8,base=10))

-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.05430567315443083
-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.056576034369974
-0.04765175565327358


# Proviamo con dati continui

In [93]:
from pandas import *
xls = ExcelFile('/Users/paolo/Documents/projects/Projects/Magre/feature_selection/data/real/ENB2012_data.xlsx')
df = xls.parse(xls.sheet_names[0])
print(df)

       X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2  Unnamed: 10  \
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33          NaN   
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33          NaN   
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33          NaN   
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33          NaN   
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28          NaN   
..    ...    ...    ...     ...  ...  ..  ...  ..    ...    ...          ...   
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  17.88  21.40          NaN   
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.54  16.88          NaN   
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  16.44  17.11          NaN   
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.48  16.61          NaN   
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.64  16.03          NaN   

     Unnamed: 11  
0            NaN  
1

In [125]:
#1) nuova libreria
X = df.loc[:,['X1','X2','X3']].to_numpy()
Y = df.loc[:,['Y1']].to_numpy()

for j in range(3):
    Xi = []
    Yi = []
    Zi = []
    for i in range(len(Y)):
        Xi.append([X[i,j]])
        Yi.append([Y[i]])
        Zi.append(np.delete(X,j,1)[i,:].tolist())
    #print(Xi[0])
    #print(Yi[0])
    #print(Zi[0])
    print(ee.cmi(Xi,Yi,Zi,k=38,base=10))

-3.857309866213148e-16
0.2105245441812621
-3.857309866213148e-16


In [118]:
# 2) scikit --> sempre poco sensato perchè fa 1 feature alla volta
Y = df.loc[:,['Y1']].to_numpy()
X = df.loc[:,'X1'].to_numpy()
Z = df.loc[:,['X2','X3']].to_numpy()

In [119]:
# MI fra X e Z
MI_XZ = mutual_info_regression(Z,X, n_neighbors=8)
MI_XZ

array([2.48636645, 1.81429287])

In [120]:
# MI fra X e (Y,Z)

ZY = np.concatenate((Z,Y.reshape(-1,1)),axis=1)
MI_XYZ = mutual_info_regression(ZY,X, n_neighbors=8)
MI_XYZ

array([2.48462451, 1.84082843, 1.50486508])

In [14]:
# salvo pickle per custom FS

In [123]:
dic = {'X':df.loc[:,['X1','X2','X3']].to_numpy(), 'Y': df.loc[:,['Y1']].to_numpy()}

In [124]:
with open('/Users/paolo/Documents/projects/Projects/Magre/feature_selection/data/real/reg_trial.pickle', 'wb') as handle:
    pickle.dump(dic, handle, protocol=pickle.HIGHEST_PROTOCOL)